### PR TITLE
Added Edit/Delete Members (Admin)

### PR DESCRIPTION
**Pull request by InspectorGadget**
**Your PR should be to the Master Branch**

## Introduction
Adding Edit/Delete for Admins to ease their workflow.

### Relevant issues
None

### Behavioural changes
None

## Follow-up
None

## Tests
image
image

### CODE REVIEW

**Comment by kklee998** [comment]
Do we log whoever edited member details?

**Comment by InspectorGadget** [comment]
That will be made available sooner or later after this. Please make an issue

**Comment by kklee998** [comment]
On the front-end, add some simple validation to show what are the validations required

ie:
(For TP field)
"TP number should begin with TP and contain 6 digits"

right now only error returned from Laravel is "Required Tag must be filled"

**Comment by InspectorGadget** [comment]
image
@kklee998 Would this suffice?

**Comment by kklee998** [comment]
As long as UI police doesn't catch us ^^

**Comment by InspectorGadget** [comment]
If he does, he is required to design us a Dashboard. I doubt he would ;P

**Comment by kklee998** [comment]
image
I updated to this

i checked the functionality, it works
if u're okay, we can merge

**Comment by InspectorGadget** [comment]
Merging...

**Pull request merged**
